dist: xenial
language: python
python:
  - "3.7"
  - "3.6"
install:
  - git fetch --unshallow || true ## required as we need it to make own gitchangelog
  - if [ -e requirements.txt ]; then pip install -r requirements.txt; fi
  - if [ -z "$DOVIS" -o "$PKG_COVERAGE" ]; then pip install coverage; fi
  ## getting test deps
  - python setup.py develop easy_install "$(./autogen.sh --get-name)[test]"
script:
  ## real tests
  - nosetests -sx .
after_success:
  - "bash <(curl -s https://codecov.io/bash)  #dovis: ignore"


## Ignored by Travis, but used internally to check packaging
dist_check:
  options:
    exclude:
      - ["v:3.6", "pkg:old"]  ## old version is breaking python 3.6 pkg_resources
  tests:
  - label: install
    matrix:
      'yes':
        - label: venv
          matrix:
            'on': |
              pip install virtualenv
              virtualenv /tmp/virtualenv
              . /tmp/virtualenv/bin/activate
            'off': |
              true
        - label: pkg
          matrix:
            old: |
              ## version 10 introduce a bug with d2to1
              pip install setuptools==9.1
              ## some ``python setup.py`` black magic do not work with d2to1 and pip ``6.0.7``
              pip install pip==1.5.6
            docker: |
              ## Using the versions of python docker images
              true
            latest: |
              ## Using the last version of pip and setuptools
              pip install pip --upgrade
              pip install setuptools --upgrade
        - label: method
          matrix:
            setup: python setup.py install
            pip+git: pip install "git+file://$PWD"
            dist:
              dist_files:
                pip install "$DIST_FILE"
        - |
          pip show -f gitchangelog
          pip list
      'no':
      - |
        ln -sf $PWD/gitchangelog /usr/local/bin/
        touch /tmp/not-installed

  - |
    cd /tmp
    mkdir test_gitchangelog
    cd test_gitchangelog
    touch a
    git init .
    git add -A .
    git config --global user.email "you@example.com"
    git config --global user.name "Your Name"
    git commit -m "first commit"
    git tag 0.0.1
    echo 'a' > b
    git add b
    git commit -m "new: added b"
    git tag 0.0.2
    DEBUG_GITCHANGELOG=1 gitchangelog
    cat <<EOF > .gitchangelog.rc
    output_engine = makotemplate("restructuredtext")
    EOF
    pip install mako
    DEBUG_GITCHANGELOG=1 gitchangelog
  - |
    [ -e /tmp/not-installed ] || pip uninstall -y gitchangelog
